### ISSUE TITLE
Allow users to customize extension popup links/shortcuts

### ISSUE THREAD

**Issue by cjavad** [bladegery/csgo-trader-extension#63]
While using your extension a feature that i felt the need for was a shortcut to my own inventory as it would make it easier for me to go back to my own inventory while checking others or just when i start up chrome to check my inventory. 

Just a simple link when you click on the extension would be something cool to have.

<img width="383" alt="Skærmbillede 2019-08-20 kl  12 42 14" src="https://user-images.githubusercontent.com/22474016/63340750-09bdb500-c348-11e9-90b2-d03efdfedfa3.png">

**Comment by bladegery** [comment]
Thanks for the idea, funnily enough I pretty much opened Github right now to open a similar issue. I think I will hijack yours and generalize it.

**Comment by bladegery** [comment]
There should be a menu in the options page that allows users to select what links they want shown in the popup. The default ones should be, about, options, changelog, bookmarks, inventory, trade offers.
I wanted to have an option menu for the popup anyway for #38 anyways.
Users could set their own custom shortcuts as well.

**Comment by bladegery** [comment]
I think it's a few hours of work and I might do it in the next few weeks.
Items to implement:

- There is already a function that checks whether the user is visiting their own inventory. There should be a key in storage.local that is updated with the steamid of the user every time they refresh their inventory page and maybe other pages too. Later when there is a login with steam option then this could be replaced.
- The list of default links in enums, loaded to storage.local on install/update.
- A menu in options that allows to: update the list of links, reset it to default, etc.

**Comment by cjavad** [comment]
So the options page would look kinda like this?

<img width="1128" alt="Skærmbillede 2019-08-21 kl  22 10 00" src="https://user-images.githubusercontent.com/22474016/63464915-7c21b880-c460-11e9-8d28-b716a5398f72.png">


```html
<div class="buildingBlock">
    <h2>Popups</h2>
    <table class="table table-striped">
        <thread>
            <tr>
                <th>Name</th>
                <th>Value</th>
                <th>Description</th>
            </tr>
        </thread>
        <tbody>
            <tr>
                <td>About</td>
                <td style="text-align:center;">
                    <label class="switch">
                        <input type="checkbox" id="aboutPopup">
                        <span class="slider round"></span>
                    </label>
                </td>
                <td>If enabled the about page will be linked as a popup</td>
            </tr>
            <tr>
                <td>Options</td>
                <td style="text-align:center;">
                    <label class="switch">
                        <input type="checkbox" id="optionsPopup">
                        <span class="slider round"></span>
                    </label>
                </td>
                <td>If enabled the options page will be linked as a popup</td>
            </tr>
            <tr>
                <td>Changelog</td>
                <td style="text-align:center;">
                    <label class="switch">
                        <input type="checkbox" id="changelogPopup">
                        <span class="slider round"></span>
                    </label>
                </td>
                <td>If enabled the changelog page will be linked as a popup</td>
            </tr>
            <tr>
                <td>Booksmarks</td>
                <td style="text-align:center;">
                    <label class="switch">
                        <input type="checkbox" id="bookmarksPopup">
                        <span class="slider round"></span>
                    </label>
                </td>
                <td>If enabled the about bookmarks will be linked as a popup</td>
            </tr>
        </tbody>
    </table>
</div>
```

**Comment by bladegery** [comment]
I think a multi select (https://www.w3schools.com/tags/att_select_multiple.asp, perhaps without the need for ctrl: https://stackoverflow.com/questions/8641729/how-to-avoid-the-need-for-ctrl-click-in-a-multi-select-box-using-javascript) would be more compact and a better fit overall, it's also much easier to make it dynamic.
The default ones added to enums like:
`const defaultPopupLinks = {
    "changelog":{
        key: "changelog",
        name: "Changelog",
        url: "https://csgotrader.app/changelog/"
    },
    "options":{
        key: "options",
        name: "Options",
        url: "chrome-extension://kaibcgikagnkfgjnibflebpldakfhfih/html/options.html"
    }
};`
It could be loaded into storage.local on install then dynamically generated in the popup and options.

**Comment by cjavad** [comment]
Tried to add the multiselect option but failed miserably. Did however implement the switch based one.

Add to options.js
```js
/ get all checkbox elements for popups
let aboutPopup = document.getElementById("aboutPopup");
let optionsPopup = document.getElementById("optionsPopup");
let changelogPopup = document.getElementById("changelogPopup");
let bookmarksPopup = document.getElementById("bookmarksPopup");

// create listeners and chrome storage functions for each one of them

chrome.storage.local.get('aboutPopup', function(result){ 
    let optionOn = result.aboutPopup;
    if (optionOn){
        aboutPopup.result = optionOn;
    }
});

aboutPopup.addEventListener("click", function () {
    chrome.storage.local.set({aboutPopup: aboutPopup.checked}, function() {});
});

chrome.storage.local.get('optionsPopup', function(result){ 
    let optionOn = result.optionsPopup;
    if (optionOn){
        optionsPopup.result = optionOn;
    }
});

optionsPopup.addEventListener("click", function () {
    chrome.storage.local.set({optionsPopup: optionsPopup.checked}, function() {});
});

chrome.storage.local.get('changelogPopup', function(result){ 
    let optionOn = result.changelogPopup;
    if (optionOn){
        changelogPopup.result = optionOn;
    }
});

changelogPopup.addEventListener("click", function () {
    chrome.storage.local.set({changelogPopup: changelogPopup.checked}, function() {});
});

chrome.storage.local.get('bookmarksPopup', function(result){ 
    let optionOn = result.bookmarksPopup;
    if (optionOn){
        bookmarksPopup.result = optionOn;
    }
});


bookmarksPopup.addEventListener("click", function () {
    chrome.storage.local.set({bookmarksPopup: bookmarksPopup.checked}, function() {});
});
```
Updated popup.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSGO Trader</title>
    <link rel="stylesheet" href="/css/thirdparty/bootstrap.min.css">
    <link rel="stylesheet" href="/css/CSTExtensionPages.css">
</head>
<body style="width: 200px; padding: 5px">
<script src="/js/thirdparty/jquery-3.3.1.min.js"></script>
<script src="/js/thirdparty/bootstrap.bundle.min.js"></script>
<div style="text-align: center">
    <a href="https://csgotrader.app" target="_blank">
        <img style="margin-bottom: 5px" src="/images/cstlogo48.png">
        <h5>CSGO Trader <span id="version"></span></h5>
    </a>
    <div id="about">
        <a href="about.html" target="_blank">About</a>
    </div>
    <div id="options">
        <a href="options.html" target="_blank">Options</a>
    </div>
    <div id="changelog"><a href="https://csgotrader.app/changelog/" target="_blank">Changelog</a>
    </div>
    <div id="bookmarks"><a href="bookmarks.html" target="_blank">Bookmarks</a>
    </div>
</div>
</div>
<script src="/js/internal_pages/popup.js"></script>
</body>
</html>
````

Updated popup.js
```
chrome.runtime.sendMessage({badgetext: ""}, function(response) {});

let version = chrome.runtime.getManifest().version;
$("#version").text(version);

// check if the popup option should be shown then show/hide depending on if it should work

chrome.storage.local.get('aboutPopup', function(result){ 
    let optionOn = result.aboutPopup;
    if (optionOn){
        $("#about").show();
    } else {
        $("#about").hide();
    }
});

chrome.storage.local.get('optionsPopup', function(result){ 
    let optionOn = result.optionsPopup;
    if (optionOn){
        $("#options").show();
    } else {
        $("#options").hide();
    }
});


chrome.storage.local.get('changelogPopup', function(result){ 
    let optionOn = result.changelogPopup;
    if (optionOn){
        $("#changelog").show();
    } else {
        $("#changelog").hide();
    }
});

chrome.storage.local.get('bookmarksPopup', function(result){ 
    let optionOn = result.bookmarksPopup;
    if (optionOn){
        $("#bookmarks").show();
    } else {
        $("#bookmarks").hide();
    }
});
```

And then of course the html of options.html from the previous code snippe.

**Comment by cjavad** [comment]
Still missing the tradelink and inventory links, those can be added easily though, but dynamic handling is harder to implement like this though as mentioned. Also need to default the 4 popups as default no clue how to do that though.

**Comment by cjavad** [comment]
Is that really a good solution though? Everything seems a bit close, maybe some kind of spacing would help (and tradeoffers on one line).

**Comment by bladegery** [comment]
@cjavad added the rest of the functionality, feel free to change the style. Just keep the dynamicity please.
This is how it looks like:
![image](https://user-images.githubusercontent.com/3636827/63643285-b479fe80-c6cd-11e9-8086-911826f61bf3.png)
Maybe we could more defaults, but in non-active state. Let me know if you have any ideas for that.
