### ISSUE TITLE
Not able to buy skins from market with SIH.

### ISSUE THREAD

**Issue by RonGokhale** [bladegery/csgo-trader-extension#71]
updated to latest version now can't buy any csgo skins from market without disabling SIH. 
buying commodity items works fine but not skins, just can't click on "Buy Now".

**Comment by bladegery** [comment]
Thanks, I can confirm that this is indeed an issue just as described.

**Comment by bladegery** [comment]
@RonGokhale thanks for the report, the fix will be in the next release.
