### ISSUE TITLE
Option to mass trade and sell items

### ISSUE THREAD

**Issue by Jason-Tam4** [bladegery/csgo-trader-extension#95]
Similar to steam inventory helper's function (for example selecting a massive amount of cases and trading all of those) and same for selling all of a certain item at a certain price

**Comment by bladegery** [comment]
@Jason-Tam4 I have just started the work on mass selling #69 last week so that is definitely coming soon. I am not sure how you mean for trading though. You can already use ctrl+click to add or remove similar (same market_hash_name) items. Let me know if you mean something else.

**Comment by Jason-Tam4** [comment]
Oh sorry didn't realize that feature was already there. I hadn't download the extension yet and was basing it off the features listed on the site. Can't wait to see the mass sell feature soon.

**Comment by bladegery** [comment]
@Jason-Tam4 I really should update that, thanks. If that is what you meant by the trading thing then I will close the issue.
